from typing import Dict, Any, Optional
from datetime import datetime
from pathlib import Path
import json
from app.core.logger import setup_logger
from app.core.file_manager import FileManager

logger = setup_logger(__name__)

class ExportService:
    """Handle export of travel guides in multiple formats"""
    
    @staticmethod
    def export_json(data: Dict[str, Any], destination: str) -> Dict[str, Any]:
        """Export as JSON"""
        try:
            filename = f"output/{destination.lower().replace(' ', '_')}_guide_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            if FileManager.save_json(data, filename):
                return {
                    "status": "success",
                    "format": "json",
                    "filename": filename,
                    "size": len(json.dumps(data))
                }
            return {"status": "error", "message": "Failed to save JSON"}
        except Exception as e:
            logger.error(f"JSON export error: {e}")
            return {"status": "error", "message": str(e)}
    
    @staticmethod
    def export_markdown(data: Dict[str, Any], destination: str) -> Dict[str, Any]:
        """Export as Markdown"""
        try:
            md_content = ExportService._generate_markdown(data, destination)
            filename = f"output/{destination.lower().replace(' ', '_')}_guide_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            if FileManager.save_markdown(md_content, filename):
                return {
                    "status": "success",
                    "format": "markdown",
                    "filename": filename,
                    "size": len(md_content),
                    "content": md_content
                }
            return {"status": "error", "message": "Failed to save Markdown"}
        except Exception as e:
            logger.error(f"Markdown export error: {e}")
            return {"status": "error", "message": str(e)}
    
    @staticmethod
    def _generate_markdown(data: Dict[str, Any], destination: str) -> str:
        """Generate markdown content"""
        md = f"# Travel Guide: {destination}\n\n"
        md += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        md += "---\n\n"
        
        if "places" in data:
            md += "## Top Places\n\n"
            for place in data.get("places", {}).get("places", [])[:10]:
                md += f"### {place.get('name', 'Unknown')}\n"
                md += f"{place.get('description', 'A must-visit destination')}\n\n"
        
        if "itinerary" in data:
            md += "## 3-Day Itinerary\n\n"
            for day in data.get("itinerary", {}).get("three_days", []):
                md += f"### Day {day.get('day', 1)}\n"
                for activity in day.get("activities", []):
                    md += f"- {activity}\n"
                md += "\n"
        
        if "food" in data:
            md += "## Must-Try Dishes\n\n"
            for dish in data.get("food", {}).get("must_try_dishes", [])[:15]:
                md += f"- {dish}\n"
            md += "\n"
        
        md += "---\n\n"
        md += "*Generated by TravelAI - Your AI-Powered Travel Companion*\n"
        
        return md
    
    @staticmethod
    def export_html(data: Dict[str, Any], destination: str) -> Dict[str, Any]:
        """Export as HTML"""
        try:
            html_content = ExportService._generate_html(data, destination)
            filename = f"output/{destination.lower().replace(' ', '_')}_guide_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
            if FileManager.save_html(html_content, filename):
                return {
                    "status": "success",
                    "format": "html",
                    "filename": filename,
                    "size": len(html_content),
                    "content": html_content
                }
            return {"status": "error", "message": "Failed to save HTML"}
        except Exception as e:
            logger.error(f"HTML export error: {e}")
            return {"status": "error", "message": str(e)}
    
    @staticmethod
    def _generate_html(data: Dict[str, Any], destination: str) -> str:
        """Generate premium HTML content"""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travel Guide: {destination}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;
            background: linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%);
            color: #ffffff;
            line-height: 1.6;
        }}
        
        .container {{
            max-width: 900px;
            margin: 0 auto;
            padding: 60px 24px;
        }}
        
        header {{
            margin-bottom: 60px;
            text-align: center;
        }}
        
        h1 {{
            font-size: 48px;
            font-weight: 700;
            margin-bottom: 12px;
            background: linear-gradient(135deg, #10a37f 0%, #0d8b6f 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}
        
        .meta {{
            color: #b3b3b3;
            font-size: 14px;
        }}
        
        section {{
            margin-bottom: 60px;
        }}
        
        h2 {{
            font-size: 32px;
            font-weight: 700;
            margin-bottom: 24px;
            color: #ffffff;
            border-bottom: 2px solid #10a37f;
            padding-bottom: 12px;
            display: flex;
            align-items: center;
            gap: 12px;
        }}
        
        .place {{
            background: rgba(45, 45, 45, 0.5);
            border: 1px solid #333333;
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 16px;
            transition: all 0.3s ease;
        }}
        
        .place:hover {{
            border-color: #10a37f;
            background: rgba(45, 45, 45, 0.8);
        }}
        
        .place h3 {{
            font-size: 20px;
            font-weight: 600;
            margin-bottom: 12px;
            color: #10a37f;
        }}
        
        .place p {{
            color: #b3b3b3;
            line-height: 1.8;
        }}
        
        .day {{
            background: rgba(16, 163, 127, 0.1);
            border-left: 4px solid #10a37f;
            padding: 24px;
            margin-bottom: 16px;
            border-radius: 8px;
        }}
        
        .day h3 {{
            font-size: 18px;
            font-weight: 600;
            margin-bottom: 16px;
            color: #10a37f;
        }}
        
        .day ul {{
            list-style: none;
            padding: 0;
        }}
        
        .day li {{
            padding: 8px 0;
            color: #b3b3b3;
            display: flex;
            align-items: center;
        }}
        
        .day li:before {{
            content: "✓";
            color: #10a37f;
            font-weight: bold;
            margin-right: 12px;
        }}
        
        .dishes {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 12px;
        }}
        
        .dish {{
            background: rgba(16, 163, 127, 0.1);
            border: 1px solid #10a37f;
            border-radius: 8px;
            padding: 16px;
            text-align: center;
            color: #b3b3b3;
            transition: all 0.3s ease;
        }}
        
        .dish:hover {{
            background: rgba(16, 163, 127, 0.2);
            color: #10a37f;
        }}
        
        footer {{
            border-top: 1px solid #333333;
            padding-top: 40px;
            margin-top: 60px;
            text-align: center;
            color: #808080;
            font-size: 13px;
        }}
        
        @media print {{
            body {{
                background: white;
                color: #000;
            }}
            .container {{
                padding: 40px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{destination}</h1>
            <p class="meta">Travel Guide • Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
        </header>
"""
        
        if "places" in data:
            html += """        <section>
            <h2>Top Places</h2>
"""
            for place in data.get("places", {}).get("places", [])[:10]:
                html += f"""            <div class="place">
                <h3>{place.get('name', 'Unknown')}</h3>
                <p>{place.get('description', 'A must-visit destination')}</p>
            </div>
"""
            html += "        </section>\n\n"
        
        if "itinerary" in data:
            html += """        <section>
            <h2>3-Day Itinerary</h2>
"""
            for day in data.get("itinerary", {}).get("three_days", []):
                html += f"""            <div class="day">
                <h3>Day {day.get('day', 1)}</h3>
                <ul>
"""
                for activity in day.get("activities", []):
                    html += f"                    <li>{activity}</li>\n"
                html += """                </ul>
            </div>
"""
            html += "        </section>\n\n"
        
        if "food" in data:
            html += """        <section>
            <h2>Must-Try Dishes</h2>
            <div class="dishes">
"""
            for dish in data.get("food", {}).get("must_try_dishes", [])[:15]:
                html += f"""                <div class="dish">{dish}</div>
"""
            html += """            </div>
        </section>
"""
        
        html += """
        <footer>
            <p>Generated by <strong>TravelAI</strong> - Your AI-Powered Travel Companion</p>
            <p>© 2025 TravelAI. All rights reserved.</p>
        </footer>
    </div>
</body>
</html>
"""
        return html
    
    @staticmethod
    def get_export_data(data: Dict[str, Any], destination: str, format: str) -> Dict[str, Any]:
        """Get export data in requested format"""
        if format == "json":
            return ExportService.export_json(data, destination)
        elif format == "markdown":
            return ExportService.export_markdown(data, destination)
        elif format == "html":
            return ExportService.export_html(data, destination)
        else:
            return {"status": "error", "message": f"Unsupported format: {format}"}
